# Generated by Django 3.2.6 on 2022-07-20 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.TextField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['set_name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('card_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='card_images')),
                ('ppoi', versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True)),
                ('cardsets', models.ManyToManyField(related_name='cards', to='flashcards.Cardset')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='flashcards', to='notes.Tag')),
            ],
        ),
    ]
