# Generated by Django 3.2.6 on 2022-07-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='tags',
        ),
    ]
